on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-18.04
    env:
      working-directory: .
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: '16.x'
          cache: 'yarn'

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install --frozen-lockfile
        working-directory: ${{ env.working-directory }}

      - name: Build
        run: CI='false' yarn build
        working-directory: ${{ env.working-directory }}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GIT_TOKEN }}
          publish_dir: ./dist
